---

- name: Install python-requests
  yum:
    name: python-requests
    state: latest

- name: Clone contrail-ansible-deployer
  git:
    repo: "{{ contrail_deployer_branch | get_deployer_repo }}"
    dest: /root/contrail-ansible-deployer
    force: yes
    version: "{{ contrail_deployer_branch }}"

- name: Populate contrail-ansible-deployer/config/instances.yaml
  template:
    src: "{{ instances_template }}"
    dest: /root/contrail-ansible-deployer/config/instances.yaml

- name: Create config directory
  file:
    path: "{{ vagrant_root }}/config"
    state: directory
  delegate_to: localhost

- name: Populate config/instances.yaml
  template:
    src: "{{ instances_template }}"
    dest: "{{ vagrant_root }}/config/instances.yaml"
  delegate_to: localhost

- name: Install kvm for DPDK vrouter
  shell:  modprobe -r kvm_intel

- name: Enable flags for nested virtualization
  shell: modprobe kvm_intel nested=1 enable_shadow_vmcs=1 enable_apicv=1 ept=1

