---
- name: Check if host_vars folder exists
  stat:
    path: "{{ vagrant_root }}/playbooks/host_vars"
  register: host_vars
  delegate_to: localhost

- name: Print if host_vars exists
  debug:
    msg: "{{ vagrant_root }}/playbooks/host_vars folder exists"
  when: host_vars.stat.exists
  delegate_to: localhost

- name: Copy directory to workspace
  file:
    path: "{{ vagrant_root }}/playbooks/host_vars"
    state: directory
  when: host_vars.stat.exists == false
  delegate_to: localhost

- name: Populate interfaces settings for switch
  template:
    src: 'switch_interface.j2'
    dest: "{{ vagrant_root }}/playbooks/host_vars/{{ switch_name }}.yaml"
  delegate_to: localhost



