---
- hosts: all
  gather_facts: no
  become: True
  tasks:
    - name: Copy kernel-957 to /tmp/
      copy:
        src: ../kernel-3.10.0-957.27.2.el7.x86_64.rpm 
        dest: /tmp/

    - name: Upgrade kernel-devel version for releases greater than 19O9
      yum:
        name: /tmp/
        state: present

    - name: Copy kernel-devel-957 to /tmp/
      copy:
        src: ../kernel-devel-3.10.0-957.27.2.el7.x86_64.rpm
        dest: /tmp/

    - name: Upgrade kernel-devel version for releases greater than 19O9
      yum:
        name: /tmp/
        state: present
    
    - name: Reboot server
      reboot:
        reboot_timeout: 300

    - name: Check if server is up
      debug:
        msg: Server is up


 
